In [2]:
import numpy as np
import pandas as pd

In [56]:
config = {
    'C_1': {'bobot': 0.225, 'tipe': 'benefit'}, # Harus Padi
    'C_2': {'bobot': 0.225, 'tipe': 'benefit'}, # KRUSIAL: Harus SVM
    'C_3': {'bobot': 0.175, 'tipe': 'benefit'}, # KRUSIAL: Harus Warna+Tekstur
    'C_4': {'bobot': 0.175, 'tipe': 'benefit'}, # Utamakan data sawah/pribadi
    'C_5': {'bobot': 0.05, 'tipe': 'benefit'}, # Akurasi tinggi itu bonus
    'C_6': {'bobot': 0.15, 'tipe': 'benefit'}  # Semakin baru semakin baik
}

|No|Peneliti & Tahun|C_1 (Obj)|C_2 (Metd)|C_3 (Fitr)|C_4 (Cond)|C_5 (Acc)|C_6 (Thn)|
|:--:|:---|:--:|:--:|:--:|:--:|:--:|:--:|
|1|Azmi et al.|2|1|1|0|0.99|2024|
|2|Sheila et al.|2|1|1|0|0.9375|2023|
|3|Oktaviana et al.|2|1|1|0|1|2021|
|4|Sethy et al.|2|3|1|1|0.9838|2020|
|5|Prajapati et al.|2|3|3|0|0.7333|2017|
|6|Ghyar & Birajdar|2|3|3|0|0.925|2017|
|7|Bashir et al.|2|3|1|0|0.9416|2019|
|8|Singh et al.|2|3|3|0|0.961|2022|
|10|Setiawan et al.|2|3|1|0|0.5381|2023|
|11|Rahman et al.|2|1|1|1|0.9433|2020|
|12|Susanto et al.|2|1|1|0|0.9647|2025|
|13|Fauzi et al.|2|1|1|0|0.932|2024|
|14|Agustiani et al.|2|2|2|0|0.9965|2022|
|15|Setiaji & Huda|2|2|2|0|0.933|2022|
|16|Purnamawati et al.|2|2|1|0|0.87|2020|
|17|Novantara et al.|2|1|1|1|0.9775|2025|
|18|Khoiruddin et al.|2|1|1|0|0.98|2022|
|19|Wagle & Harikrishnan|1|3|1|0|0.9115|2021|
|20|Burhanuddin|2|2|3|1|0.76|2024|
|21|Agustina et al.|2|1|1|0|0.9917|2024|
|23|Kusanti & Haris|2|2|2|1|0.80|2018|
|24|Rustanto et al.|2|2|2|0|0.9167|2024|
|25|Sarasati|2|1|1|1|0.9453|2021|
|26|Naresh kumar & Sakthivel|2|2|1|0|0.976|2025|
|28|Yao et al.|2|3|3|1|0.972|2009|
|29|Devi & Neelamegam|2|3|3|1|0.9863|2019|
|30|Hasan et al.|2|3|1|1|0.975|2019|
|31|Jiang et al.|2|3|1|1|0.968|2020|
|32|Verawati & Aunurrohim|2|2|2|0|0.9167|2024|
|33|Milano|2|1|1|0|0.7705|2024|
|35|Saputra et al.|2|1|1|0|0.92|2021|
|36|Wenda et al.|2|2|3|0|0.907|2020|
|37|Hatuwal et al.|1|1|1|0|0.9789|2020|
|38|Pothen & Pai|2|3|2|0|0.946|2020|
|43|Das et al.|1|3|2|0|0.876|2020|
|44|Santosa et al.|2|1|1|0|0.9966|2023|
|45|Shah et al.|2|1|1|0|0.9975|2023|
|46|Istiqomah & Murinto|2|1|1|0|0.93|2024|
|47|Murniyasih & Suryani|2|2|1|1|0.75|2020|
|48|Hartono et al.|2|1|1|0|0.9375|2025|

No,"Peneliti & Tahun",C_1,C_2,C_3,C_4,C_5,C_6
1,"Azmi et al.",2,1,1,0,0.99,2024
2,"Sheila et al.",2,1,1,0,0.9375,2023
3,"Oktaviana et al.",2,1,1,0,1,2021
4,"Sethy et al.",2,3,1,1,0.9838,2020
5,"Prajapati et al.",2,3,3,0,0.7333,2017
6,"Ghyar & Birajdar",2,3,3,0,0.925,2017
7,"Bashir et al.",2,3,1,0,0.9416,2019
8,"Singh et al.",2,3,3,0,0.961,2022
10,"Setiawan et al.",2,3,1,0,0.5381,2023
11,"Rahman et al.",2,1,1,1,0.9433,2020
12,"Susanto et al.",2,1,1,0,0.9647,2025
13,"Fauzi et al.",2,1,1,0,0.932,2024
14,"Agustiani et al.",2,2,2,0,0.9965,2022
15,"Setiaji & Huda",2,2,2,0,0.933,2022
16,"Purnamawati et al.",2,2,1,0,0.87,2020
17,"Novantara et al.",2,1,1,1,0.9775,2025
18,"Khoiruddin et al.",2,1,1,0,0.98,2022
19,"Wagle & Harikrishnan",1,3,1,0,0.9115,2021
20,"Burhanuddin",2,2,3,1,0.76,2024
21,"Agustina et al.",2,1,1,0,0.9917,2024
23,"Kusanti & Haris",2,2,2,1,0.80,2018
24,"Rustanto et al.",2,2,2,0,0.9167,2024
25,"Sarasati",2,1,1,1,0.9453,2021
26,"Naresh kumar & Sakthivel",2,2,1,0,0.976,2025
28,"Yao et al.",2,3,3,1,0.972,2009
29,"Devi & Neelamegam",2,3,3,1,0.9863,2019
30,"Hasan et al.",2,3,1,1,0.975,2019
31,"Jiang et al.",2,3,1,1,0.968,2020
32,"Verawati & Aunurrohim",2,2,2,0,0.9167,2024
33,"Milano",2,1,1,0,0.7705,2024
35,"Saputra et al.",2,1,1,0,0.92,2021
36,"Wenda et al.",2,2,3,0,0.907,2020
37,"Hatuwal et al.",1,1,1,0,0.9789,2020
38,"Pothen & Pai",2,3,2,0,0.946,2020
43,"Das et al.",1,3,2,0,0.876,2020
44,"Santosa et al.",2,1,1,0,0.9966,2023
45,"Shah et al.",2,1,1,0,0.9975,2023
46,"Istiqomah & Murinto",2,1,1,0,0.93,2024
47,"Murniyasih & Suryani",2,2,1,1,0.75,2020
48,"Hartono et al.",2,1,1,0,0.9375,2025

In [32]:
df_data = pd.read_csv('seleksi bab 2.txt', index_col=0)
df_data.sort_values('C_6')

            Peneliti & Tahun  C_1  C_2  C_3  C_4     C_5   C_6
No
28                Yao et al.    2    3    3    1  0.9720  2009
6           Ghyar & Birajdar    2    3    3    0  0.9250  2017
5           Prajapati et al.    2    3    3    0  0.7333  2017
23           Kusanti & Haris    2    2    2    1  0.8000  2018
30              Hasan et al.    2    3    1    1  0.9750  2019
29         Devi & Neelamegam    2    3    3    1  0.9863  2019
7              Bashir et al.    2    3    1    0  0.9416  2019
4               Sethy et al.    2    3    1    1  0.9838  2020
16        Purnamawati et al.    2    2    1    0  0.8700  2020
11             Rahman et al.    2    1    1    1  0.9433  2020
36              Wenda et al.    2    2    3    0  0.9070  2020
31              Jiang et al.    2    3    1    1  0.9680  2020
47      Murniyasih & Suryani    2    2    1    1  0.7500  2020
43                Das et al.    1    3    2    0  0.8760  2020
38              Pothen & Pai    2    3    2    0  0.9460  2020
37            Hatuwal et al.    1    1    1    0  0.9789  2020
19      Wagle & Harikrishnan    1    3    1    0  0.9115  2021
25                  Sarasati    2    1    1    1  0.9453  2021
3           Oktaviana et al.    2    1    1    0  1.0000  2021
35            Saputra et al.    2    1    1    0  0.9200  2021
8               Singh et al.    2    3    3    0  0.9610  2022
18         Khoiruddin et al.    2    1    1    0  0.9800  2022
15            Setiaji & Huda    2    2    2    0  0.9330  2022
14          Agustiani et al.    2    2    2    0  0.9965  2022
2              Sheila et al.    2    1    1    0  0.9375  2023
10           Setiawan et al.    2    3    1    0  0.5381  2023
45               Shah et al.    2    1    1    0  0.9975  2023
44            Santosa et al.    2    1    1    0  0.9966  2023
33                    Milano    2    1    1    0  0.7705  2024
24           Rustanto et al.    2    2    2    0  0.9167  2024
13              Fauzi et al.    2    1    1    0  0.9320  2024
1                Azmi et al.    2    1    1    0  0.9900  2024
21           Agustina et al.    2    1    1    0  0.9917  2024
20               Burhanuddin    2    2    3    1  0.7600  2024
46       Istiqomah & Murinto    2    1    1    0  0.9300  2024
32     Verawati & Aunurrohim    2    2    2    0  0.9167  2024
26  Naresh kumar & Sakthivel    2    2    1    0  0.9760  2025
17          Novantara et al.    2    1    1    1  0.9775  2025
12            Susanto et al.    2    1    1    0  0.9647  2025
48            Hartono et al.    2    1    1    0  0.9375  2025

In [33]:
df_C_only = df_data.drop(['Peneliti & Tahun'], axis=1)
df_C_only.head()

    C_1  C_2  C_3  C_4     C_5   C_6
No
1     2    1    1    0  0.9900  2024
2     2    1    1    0  0.9375  2023
3     2    1    1    0  1.0000  2021
4     2    3    1    1  0.9838  2020
5     2    3    3    0  0.7333  2017

In [57]:
df_calc = df_C_only.copy()
df_norm = pd.DataFrame()
kriteria_cols = list(config.keys())

for col, settings in config.items():
    if settings['tipe']=='benefit':
        df_norm[col] = df_calc[col]/df_calc[col].max()
    elif settings['tipe']=='cost':
        df_norm[col] = df_calc[col].min()/df_calc[col]

df_weighted = df_norm.copy()
for col, settings in config.items():
    df_weighted[col] = df_norm[col] * settings['bobot']
    
ideal_positif = {}
ideal_negatif = {}

for col in kriteria_cols:
    # Karena sudah dinormalisasi SAW (Benefit semua arahnya positif), 
    # maka Ideal Positif selalu Max, Negatif selalu Min
    ideal_positif[col] = df_weighted[col].max()
    ideal_negatif[col] = df_weighted[col].min()
    
def get_distance(row, ideal_dict):
        dist = 0
        for col in kriteria_cols:
            dist += (row[col] - ideal_dict[col]) ** 2
        return np.sqrt(dist)

df_calc['D_plus'] = df_weighted.apply(lambda x: get_distance(x, ideal_positif), axis=1)
df_calc['D_min'] = df_weighted.apply(lambda x: get_distance(x, ideal_negatif), axis=1)

df_calc['Skor_Akhir'] = df_calc['D_min'] / (df_calc['D_min'] + df_calc['D_plus'])

df_calc.sort_values(by='Skor_Akhir', ascending=False)

    C_1  C_2  C_3  C_4     C_5   C_6    D_plus     D_min  Skor_Akhir
No
29    2    3    3    1  0.9863  2019  0.000817  0.282657    0.997119
28    2    3    3    1  0.9720  2009  0.001834  0.282600    0.993551
20    2    2    3    1  0.7600  2024  0.075954  0.250283    0.767182
23    2    2    2    1  0.8000  2018  0.095541  0.229087    0.705691
4     2    3    1    1  0.9838  2020  0.116670  0.257446    0.688145
30    2    3    1    1  0.9750  2019  0.116674  0.257408    0.688106
31    2    3    1    1  0.9680  2020  0.116678  0.257379    0.688074
47    2    2    1    1  0.7500  2020  0.139257  0.221403    0.613883
8     2    3    3    0  0.9610  2022  0.175011  0.221845    0.559007
6     2    3    3    0  0.9250  2017  0.175041  0.221680    0.558780
5     2    3    3    0  0.7333  2017  0.175508  0.221050    0.557421
17    2    1    1    1  0.9775  2025  0.190033  0.209202    0.524007
25    2    1    1    1  0.9453  2021  0.190049  0.209037    0.523789
11    2    1    1    1  0.9433  2020  0.190051  0.209027    0.523775
38    2    3    2    0  0.9460  2020  0.184486  0.197423    0.516936
36    2    2    3    0  0.9070  2020  0.190451  0.179536    0.485249
7     2    3    1    0  0.9416  2019  0.210345  0.188584    0.472726
10    2    3    1    0  0.5381  2023  0.211588  0.187503    0.469825
43    1    3    2    0  0.8760  2020  0.216154  0.161830    0.428139
14    2    2    2    0  0.9965  2022  0.199130  0.149031    0.428052
15    2    2    2    0  0.9330  2022  0.199158  0.148576    0.427269
32    2    2    2    0  0.9167  2024  0.199174  0.148471    0.427077
24    2    2    2    0  0.9167  2024  0.199174  0.148471    0.427077
19    1    3    1    0  0.9115  2021  0.238562  0.151160    0.387866
26    2    2    1    0  0.9760  2025  0.223299  0.136975    0.380196
16    2    2    1    0  0.8700  2020  0.223391  0.136225    0.378807
3     2    1    1    0  1.0000  2021  0.258334  0.114850    0.307757
45    2    1    1    0  0.9975  2023  0.258333  0.114826    0.307712
44    2    1    1    0  0.9966  2023  0.258333  0.114817    0.307696
21    2    1    1    0  0.9917  2024  0.258334  0.114769    0.307607
1     2    1    1    0  0.9900  2024  0.258334  0.114752    0.307575
18    2    1    1    0  0.9800  2022  0.258335  0.114653    0.307391
12    2    1    1    0  0.9647  2025  0.258339  0.114510    0.307122
48    2    1    1    0  0.9375  2025  0.258352  0.114265    0.306655
2     2    1    1    0  0.9375  2023  0.258352  0.114263    0.306652
13    2    1    1    0  0.9320  2024  0.258356  0.114216    0.306562
46    2    1    1    0  0.9300  2024  0.258357  0.114199    0.306529
35    2    1    1    0  0.9200  2021  0.258364  0.114112    0.306361
33    2    1    1    0  0.7705  2024  0.258588  0.113104    0.304295
37    1    1    1    0  0.9789  2020  0.281769  0.022055    0.072592